### PR TITLE
elements page and single line element and buttons

### PR DESCRIPTION
**Pull request by RapidVinay**
Created the master page which will house links to all the elements. 
The master page has the description of element id, element title etc.
Also created the first element - Single line attribute fields description.

### CODE REVIEW

**Comment by RapidVinay** [comment]
I am writing Buttons description... Instead of creating a new PR.. I added the same to this one.. as it is still open.. So please review Buttons as well.. Some final few paragraphs are left in buttons, though.

**Review by thealexclub — APPROVED** [review]
👍

**Comment by RapidVinay** [comment]
It seems this needs to be merged with main now.. The main has got the buttons.md .. but I cant seem to find the input elements.. the single line and other short ones which Matt created for structuring the controls directory are missing from main.. 

If you are happy with everything, please bring everything to main... I tried to close and merge... it said some conflict needs to be resolved.. This is my worst fear.. to lose documents like this...

**Review by MattFranklin-Rapid — APPROVED** [review]
Yeah nice, there sure is a lot more about setting up a button than was in my mind. Goes to show how flexible this all is I suppose.

Everything builds as expected and the links are working!

**Comment by MattFranklin-Rapid** [comment]
Fixed up merge conflicts and merging in!

**Pull request merged**
